.TH HOMA_SEND 3 2019-02-15 "Homa" "Linux Programmer's Manual"
.SH NAME
homa_send \- send a request message
.SH SYNOPSIS
.nf
.B #include <homa.h>
.PP
.BI "int homa_send(int " sockfd ", const void *" request ", size_t " \
reqlen ,
.BI "              const struct sockaddr *" dest_addr ", size_t " \
addrlen  ,
.BI "              uint64_t *" id );
.fi
.SH DESCRIPTION
The function
.BR homa_send ()
transmits a request message using the Homa transport protocol.
The argument
.I sockfd
is the file descriptor of the sending socket; this must be a Homa socket.
The request message is stored in a buffer pointed to by
.IR request .
The argument 
.I reqlen
gives the length of the message in bytes, which must not exceed
.BR HOMA_MAX_MESSAGE_LENGTH .
The destination socket for the request is given by
.I dest_addr
and
.I addrlen .
If
.I id
is not NULL, an identifier for the request is returned at
.IR *id.
The identifier is unique among all requests issued on
.IR sockfd ,
and can be used to match the request with a response returned later by
.BR homa_reply (3).
.PP
This function returns as soon as the message has been queued for
transmission.

.SH RETURN VALUE
On success, the return value is 0 and an identifier for the reqest
is stored at
.I *id
(if
.I id
is not NULL). The  identifier can be used later to match the request
with the corresponding response, using
.BR homa_reply (3).
On error, \-1 is returned and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B EAFNOSUPPORT
The address family specified by
.I dest_addr
is not supported by Homa.
.TP
.B EBADF
.I sockfd
is not a valid open file descriptor.
.TP
.B EFAULT
An invalid user space address was specified for an argument.
.TP
.B EINTR
A signal occurred before any data was transmitted; see
.BR signal (7).
.TP
.B EINVAL
The size of the request exceeded
.B HOMA_MAX_MESSAGE_LENGTH, or
.I sockfd
was not a Homa socket.
.TP
.B ENOMEM
No memory available.
.TP
.B ESHUTDOWN
The socked has been disabled using
.BR shutdown (2).
.SH SEE ALSO
.BR homa_invoke (3),
.BR homa_recv (3),
.BR homa_reply (3),
.BR homa (7)
