.TH HOMA_ABORT 3 2021-08-24 "Homa" "Linux Programmer's Manual"
.SH NAME
homa_abort \- terminate an outgoing RPC
.SH SYNOPSIS
.nf
.B #include <homa.h>
.PP
.BI "int homa_abort(int " sockfd ", uint64_t " id );
.fi
.SH DESCRIPTION
Frees all resources associated with an RPC.
The
.I id
argument contains the identifier for an RPC that was previously sent on
.IR sockfd .
All state related to this RPC will be deleted (the RPC will not
be returned by
.BR homa_recv ).
The server for the RPC
is not notified that the RPC has been aborted. If the
request has already been transmitted to the server at the time
.B homa_abort
is invoked, it may still be executed on the server. Any response
from the server will be discarded.

.SH RETURN VALUE
On success, the return value is 0.
On error, \-1 is returned and
.I errno
is set appropriately.

.SH ERRORS
.TP
.B EINVAL
There is no RPC corresponding to
.IR id .
.SH SEE ALSO
.BR homa_recv (3),
.BR homa_reply (3),
.BR homa_send (3),
.BR homa (7)
