.TH HOMA_RECV 3 2019-02-15 "Homa" "Linux Programmer's Manual"
.SH NAME
homa_recv \- receive a Homa message
.SH SYNOPSIS
.nf
.B #include <homa.h>
.PP
.BI "ssize_t homa_recv(int " sockfd ", const void *" buf ", size_t " len ,
.BI "                  int " flags ", uint64_t *" id ,
.BI "                  const struct sockaddr *" src_addr ", size_t " \
*addrlen );
.fi
.SH DESCRIPTION
The function
.BR homa_recv ()
waits for an incoming Homa message and returns it.
The argument
.I sockfd
is the file descriptor of the receiving socket; this must be a Homa socket.
The incoming message will be stored in the buffer pointed to by
.IR buf .
The argument
.I len
indicates the number of bytes available for the message; if the actual
message is larger than
.IR len ,
then excess bytes will be discarded.
.PP
The arguments
.IR flags " and " id
select which messsage to receive and determine whether or
not the call should block if an appropriate message isn't available.
The argument
.IR flags
is an ORed combination of the following values:
.TP
.B HOMA_RECV_REQUEST
A request message may be returned.
.TP
.B HOMA_RECV_RESPONSE
A response message may be returned.
.TP
.B HOMA_RECV_NONBLOCKING
If no appropriate message is available, the call will return immediately
with an
.B EAGAIN
error, rather than blocking.
.LP
At least one of
.BR HOMA_RECV_REQUEST " and " HOMA_RECV_RESPONSE
must be set.
If the initial value of
.I *id
is nonzero then a response message will be returned only if its
id matches this value
.RB ( HOMA_RECV_REQUEST
must also be set in
.IR flags ).
.PP
The identifier for the message is returned at
.IR *id .
If
.I src_addr
is not NULL, the source address for the message is placed in the buffer
pointed to by
.IR src_addr .
The argument
.I addrlen
is a value-result argument.
Before the call, it should be initialized to the size of the
buffer associated with
.IR src_addr .
Upon return,
.I *addrlen
is updated to contain the actual size of the source address.
The returned address is truncated  if  the buffer provided is too small;
in this case,
.I *addrlen
will return a value greater than was supplied to the call.
.PP
If both
.BR HOMA_RECV_REQUEST " and " HOMA_RECV_RESPONSE
are specified in
.IR flags ,
then the message returned may be either a request or a response.
The port number stored in
.I src_addr
can be used to distinguish requests from responses.
A port number of
.B HOMA_MIN_CLIENT_PORT
or greater indicates that the message is a request;
a port number less than
.B HOMA_MIN_CLIENT_PORT
indicates that the message is a response.
.PP
If the message is a request, then the caller must eventually invoke
.BR homa_reply (3)
to respond (Homa retains state for the request until
.BR homa_reply (3)
is invoked). 

.SH RETURN VALUE
On success, the return value is the size of the response message,
which may be greater than
.IR resplen .
On error, \-1 is returned and
.I errno
is set appropriately.
.SH ERRORS
.TP
.B EAGAIN
No appropriate message was available and
.B HOMA_RECV_NONBLOCKING
was specified in
.IR flags .
.TP
.B EBADF
.I sockfd
is not a valid open file descriptor.
.TP
.B EFAULT
An invalid user space address was specified for an argument.
.TP
.B EHOSTUNREACH
No route could be found to the destination host.
.TP
.B EINTR
A signal occurred before a message was received; see
.BR signal (7).
.TP
.B EINVAL
The file descriptor
.I sockfd
did not refer to a Homa socket, or the argument
.I flags
did not contain either
.BR HOMA_RECV_REQUEST " or " HOMA_RECV_RESPONSE ,
or there was no outstanding request with an id matching
.IR *id .
.TP
.B EPROTONOSUPPORT
The destination machine does not support the Homa protocol.
.TP
.B ENOMEM
No memory available.
.TP
.B ESHUTDOWN
The socked has been disabled using
.BR shutdown (2).
.TP
.B ETIMEDOUT
The destination server did not respond to protocol requests.
.SH SEE ALSO
.BR homa_invoke (3),
.BR homa_reply (3),
.BR homa_send (3),
.BR homa (7)
