# SPDX-License-Identifier: BSD-2-Clause or GPL-2.0+
#
# Makefile for the Linux implementation of the Homa transport protocol.

obj-$(CONFIG_HOMA) := homa.o
homa-y:=        homa_incoming.o \
		homa_interest.o \
		homa_outgoing.o \
		homa_pacer.o \
		homa_peer.o \
		homa_plumbing.o \
		homa_pool.o \
		homa_rpc.o \
		homa_sock.o \
		homa_timer.o \
		homa_utils.o
