#!/bin/sh
# This script copies modified information from this directory to the machines
# given by the arguments (defaults to rcmaster if no arguments).

if [ $# -eq 0 ]; then
    targets=rcmaster.scs.stanford.edu
    dir=remote/homaModule/
else
    targets=$*
    dir=homaModule/
fi

for t in $targets; do
    echo $t
    rsync -rtv --exclude-from=rsync-exclude.txt ./ ouster@$t:$dir
done
