#!/bin/sh
# This script takes one or more node names as arguments, and copies various
# files to those nodes to set them up for Homa experiments.

for t in $*; do
    echo $t
    rsync -rtv ~/code/ramcloud/scripts/ttsum.py \
        ~/code/ramcloud/scripts/ttgrep.py ~/code/homaModule/cloudlab/bin/ $t:bin/
    rsync -rtv ~/.ssh/cloudlab_rsa.pub ~/.ssh/cloudlab_rsa $t:.ssh/
    ssh $t 'if [ ! -e .ssh/id_rsa ]; then
        cat .ssh/cloudlab_rsa.pub >> .ssh/authorized_keys
        cp .ssh/cloudlab_rsa .ssh/id_rsa
        fi'
done
