#!/bin/sh
# This script copies modified information from this directory to the
# CloudLab machines given by the arguments (defaults are provided if no
# arguments).

if [ $# -eq 0 ]; then
    # targets="ms0919.utah.cloudlab.us ms0903.utah.cloudlab.us"
    targets="hp078.utah.cloudlab.us"
else
    targets=$*
fi

for t in $targets; do
    echo $t
    rsync -rtv --exclude-from=rsync-exclude.txt ./ ouster@$t:homaModule/
done
for t in $targets; do
    echo $t
    rsync -rtv cloudlab/bin/ ouster@$t:bin/
    rsync -rtv cloudlab/bash_profile ouster@$t:.bash_profile
    rsync -rtv cloudlab/bashrc ouster@$t:.bashrc
    rsync -rtv ~/.ssh/cloudlab_rsa.pub ~/.ssh/cloudlab_rsa $t:.ssh/
    ssh $t 'if [ ! -e .ssh/id_rsa ]; then
        cp .ssh/cloudlab_rsa .ssh/id_rsa
        fi'
done
