#!/usr/bin/python3

# Copyright (c) 2020-2022 Homa Developers
# SPDX-License-Identifier: BSD-1-Clause

# This cperf benchmark measures the throughput of a single server as a
# function of the number of receiving ports

from cperf import *

parser = get_parser(description=
        'Measures throughput of a single server as a function of the number '
        ' of receiving ports.',
        usage='%(prog)s [options]',
        defaults={
            "server_ports":   6,
            "port_threads":   3})
options = parser.parse_args()
options.no_rtt_files = True
init(options)
if options.num_nodes < 2:
    print("--num_nodes too small (%d): must be at least 2"
            % (options.num_nodes))
    sys.exit(-1)
dir = "%s/reports" % (options.log_dir)
if not os.path.exists(dir):
    os.makedirs(dir)

options.server_nodes = 1
options.first_server = 0
options.client_ports = 5
options.tcp_client_ports = 5
options.port_receivers = 2
options.no_rtt_files = True
options.gbps = 0.0
# workloads = ["w1", "w2", "w3", "w4", "w5"]
workloads = ["w2", "w4"]
if options.protocol == "homa":
    port_range = range(1, (20//options.port_threads) + 1)
else:
    port_range = range(2, 21, 2)

print("port_range: %s" % (port_range))

# Run the experiments, if desired
if not options.plot_only:
    for ports in port_range:
        options.server_ports = ports
        options.tcp_server_ports = ports
        start_servers(range(0,1), options)
        for workload in workloads:
            exp = "%s_%s_%d" % (options.protocol, workload, ports)
            options.workload = workload
            run_experiment(exp, range(1, options.num_nodes), options)
    log("Stopping nodes")
    stop_nodes()

# Parse the log files to extract useful data
experiments = {}
scan_log(options.log_dir + "/node0.log", "node0", experiments)

# Keys are workload names, values are lists of throughputs for each
# number of ports
tput = {}

for workload in workloads:
    tput[workload] = []
    for ports in port_range:
        exp = "%s_%s_%d" % (options.protocol, workload, ports)
        print("Experiment %s: %s" % (exp, experiments[exp]))
        node = experiments[exp]["node0"]
        readings = node["server_kops"]
        if len(readings) == 0:
            raise Error("No RPC throughput found for experiment %s"
                    % (exp))
        tput[workload].append(sum(readings)/len(readings))

fig, (ax1, ax2) = plt.subplots(2, figsize=[4, 5])
fig.suptitle("%s Single-Server Throughput" % (options.protocol.capitalize()),
        y=0.95)
plt.rcParams.update({'font.size': 10})
ax1.set_ylim(0, 2000)
ax2.set_ylim(0, 60)
for axis in [ax1, ax2]:
    axis.get_xaxis().set_tick_params(direction='in')
    axis.get_yaxis().set_tick_params(direction='in')
    axis.set_xlim(0, port_range[-1])
    top = axis.twiny()
    top.set_xlim(0, port_range[-1])
    top.set_xticklabels([])
    top.get_xaxis().set_tick_params(direction='in')

    axis.set_ylabel("Kops/second")
    right = axis.twinx()
    right.set_ylim(0, axis.get_ylim()[1])
    right.set_yticklabels([])
    right.get_yaxis().set_tick_params(direction='in')
ax1.grid(axis='y', which='major', linestyle='dotted')
ax2.set_xlabel("Receiving ports")
ax2.grid(axis='y', which='major', linestyle='dotted')
colors = ['#9467bd', '#d62728', '#2ca02c', '#ff7f0e', '#1f77b4']
for workload in workloads:
    if (workload == "w4") or (workload == "w5"):
        ax2.plot(port_range, tput[workload], label=workload, color=colors.pop())
    else:
        ax1.plot(port_range, tput[workload], label=workload, color=colors.pop())

ax1.legend(loc="upper left", prop={'size': 9})
ax2.legend(loc="upper left", prop={'size': 9})
# plt.tight_layout()
plt.savefig("%s/reports/%s_server_tput.pdf" % (options.log_dir, options.protocol))