#!/usr/bin/python3

# Copyright (c) 2020-2022 Stanford University
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# This cperf benchmark compares the performance of Homa with TCP.
# Type "cp_vs_tcp --help" for documentation.

from cperf import *

load_info = [["w2", 3.2], ["w3", 14], ["w4", 20], ["w5", 20]]

parser = get_parser(description=
        'Measures slowdown as a function of message size for Homa and TCP.',
        usage='%(prog)s [options]')
parser.add_argument('--tcp', dest='tcp', type=boolean,
        default=True, help="Boolean value: indicates whether measurements "
                "should be run on TCP (default: true)")
parser.add_argument('--dctcp', dest='dctcp', type=boolean,
        default=False, help="Boolean value:: indicates whether measurements "
                "should be run on DCTCP (default: false)")
parser.add_argument('--servers', dest='num_servers', type=int, metavar='count',
        default=0, help="If nonzero, clients and servers will be segregated "
        "and this value indicates the number of server nodes; all other "
        "nodes will be clients. If 0, each node runs both a client and a "
        "server (default: 0)")
options = parser.parse_args()
init(options)

bw_multiplier = 0.5
if options.num_servers > 0:
    if options.num_servers >= options.num_nodes:
        raise Error("Illegal value %d for --servers option; must be less "
                "than --nodes (%d)" % (options.num_servers,
                options.num_nodes))
    options.servers = options.nodes[0:options.num_servers]
    options.clients = options.nodes[options.num_servers:len(options.nodes)]
    options.server_ports = options.server_ports * 2
    options.client_ports = options.client_ports * 2
    options.tcp_server_ports = options.tcp_server_ports * 2
    options.tcp_client_ports = options.tcp_client_ports * 2
    bw_multiplier = min(len(options.servers), len(options.clients)) \
            / len(options.clients)

if options.workload != "":
    load_info = [[options.workload, options.gbps]]

# First, run all of the experiments
if not options.plot_only:
    congestion = get_sysctl_parameter("net.ipv4.tcp_congestion_control")
    for workload, bw in load_info:
        options.workload = workload
        options.gbps = bw * bw_multiplier
        unloaded_exp = "unloaded_" + workload
        homa_exp = "homa_" + workload
        tcp_exp = "tcp_" + workload
        dctcp_exp = "dctcp_" + workload
        try:
            options.protocol = "homa"
            start_servers(options.nodes[1:2], options)

            o = copy.deepcopy(options)
            o.gbps = 0.0
            o.client_ports = 1
            o.client_max = 1
            o.server_ports = 1
            o.server_nodes = 1
            o.first_server = 1
            o.unloaded = 500
            run_experiment(unloaded_exp, options.nodes[0:1], o)

            start_servers(options.servers, options)
            run_experiment(homa_exp, options.clients, options)

            if options.tcp:
                options.protocol = "tcp"
                set_sysctl_parameter("net.ipv4.tcp_congestion_control",
                        "cubic", range(0, options.num_nodes))
                start_servers(options.servers, options)
                run_experiment(tcp_exp, options.clients, options)

            if options.dctcp:
                options.protocol = "tcp"
                set_sysctl_parameter("net.ipv4.tcp_congestion_control",
                        "dctcp", range(0, options.num_nodes))
                start_servers(options.servers, options)
                run_experiment(dctcp_exp, options.clients, options)
        except Exception as e:
            log(traceback.format_exc())

    if options.tcp or options.dctcp:
        print("Resetting TCP congestion control to %s" % (congestion))
        set_sysctl_parameter("net.ipv4.tcp_congestion_control", congestion,
                range(0, options.num_nodes))
    log("Stopping nodes")
    stop_nodes()
    scan_logs()

# Generate plots and reports
for workload, bw in load_info:
    unloaded_exp = "unloaded_" + workload
    homa_exp = "homa_" + workload
    tcp_exp = "tcp_" + workload
    dctcp_exp = "dctcp_" + workload

    set_unloaded(unloaded_exp)

    # Generate slowdown plot.
    log("Generating slowdown plot for %s" % (workload))
    title = "%s %d nodes, %.1f Gbps" % (workload.capitalize(),
            options.num_nodes, bw)
    ax = start_slowdown_plot(title, 1000, homa_exp)
    if options.tcp:
        plot_slowdown(ax, tcp_exp, "p99", "TCP P99", color=tcp_color)
        plot_slowdown(ax, tcp_exp, "p50", "TCP P50", color=tcp_color2)
    if options.dctcp:
        plot_slowdown(ax, dctcp_exp, "p99", "DCTCP P99", color=dctcp_color)
        plot_slowdown(ax, dctcp_exp, "p50", "DCTCP P50", color=dctcp_color2)
    plot_slowdown(ax, homa_exp, "p99", "Homa P99", color=homa_color)
    plot_slowdown(ax, homa_exp, "p50", "Homa P50", color=homa_color2)
    ax.legend(loc="upper right", prop={'size': 9})
    plt.tight_layout()
    plt.savefig("%s/reports/vs_tcp_%s.pdf" % (options.log_dir, workload))

    # Generate CDF of small-message RTTs.
    log("Generating short message CDF for %s" % (workload))
    unloaded_x, unloaded_y = get_short_cdf(unloaded_exp)
    homa_x, homa_y = get_short_cdf(homa_exp)
    if options.tcp:
        tcp_x, tcp_y = get_short_cdf(tcp_exp)
    if options.dctcp:
        dctcp_x, dctcp_y = get_short_cdf(dctcp_exp)
    start_cdf_plot(title, 10, 0.99e05, 1e-05, "RTT (usecs)",
            "Cumulative Fraction Short Messages")
    if options.tcp:
        plt.plot(tcp_x, tcp_y, label="TCP", color=tcp_color)
    if options.dctcp:
        plt.plot(dctcp_x, dctcp_y, label="DCTCP", color=dctcp_color)
    plt.plot(homa_x, homa_y, label="Homa", color=homa_color)
    plt.plot(unloaded_x, unloaded_y, label="Homa best case", color=unloaded_color)
    plt.legend(loc="upper right", prop={'size': 9})
    plt.savefig("%s/reports/short_cdf_%s.pdf" % (options.log_dir, workload))
